version: '3.8'

services:
  ollama:
    image: pedroeuropeu/ollama-gpt:v1
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    restart: always

  web:
    image: pedroeuropeu/ollama-web-chat:v1
    container_name: nginx-web
    ports:
      - "80:80"
    environment:
      - OLLAMA_URL=http://192.168.1.75:11434
      - OLLAMA_MODEL=llama2
    depends_on:
      - ollama
    restart: always

volumes:
  ollama:
